# Generated by Django 5.0.6 on 2024-12-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_tasks_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
